### ISSUE TITLE
Ghost menuseparator elements

### ISSUE THREAD

**Issue by MihkelMK** [Pkcarreno/cleaner-bookmark-menu#1]
I encountered an issue, where hiding the elements worked, but they left these ghost `menuseparator` elements
![Image](https://github.com/user-attachments/assets/f0a06244-199b-49c1-88db-953660978e61)

This bit of additional code fixed my issue:
```css
  #BMB_bookmarksPopup > menuseparator {
    display: none;
  }
```
![Image](https://github.com/user-attachments/assets/5b72810f-545c-4d0d-abef-7a664a38edee)

Is this a case of user error somehow or did I run into a yet-to-be-dealt-with edge case?
